### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: 'config/config.yml'

### ISSUE THREAD

**Issue by antoine19** [mtakaki/cachet-url-monitor#75] opened 2019-11-20 22:14 UTC
Hello,

Sorry but i may sounds weird because i am  bit confused on how to run with docker.
I first pull the image from the docker hub and then i get an erroor with this command:

docker run --rm -it -v "$PWD":/usr/src/app/config/ mtakaki/cachet-url-monitor

and i get this : 

Traceback (most recent call last):
  File "./cachet_url_monitor/scheduler.py", line 90, in <module>
    scheduler = Scheduler(sys.argv[1])
  File "./cachet_url_monitor/scheduler.py", line 56, in __init__
    self.configuration = Configuration(config_file)
  File "/usr/local/lib/python3.7/site-packages/cachet_url_monitor-0.5-py3.7.egg/cachet_url_monitor/configuration.py", line 84, in __init__
    self.data = load(open(self.config_file, 'r'), Loader=FullLoader)
IsADirectoryError: [Errno 21] Is a directory: 'config/config.yml'

I am a bit confused if i need to clone the repository or i just need to add a yml on my current directory . Also i was wondering if i need to get the repository to the yml file (/usr/src/app/config/) in my current directory.
Thank you in advance for the answers

**Comment by mtakaki** [comment] 2019-11-22 16:48
You just need to add a yaml file in your directory. Do you have a local `config.yml` in your directory? It sounds like it's a directory, not a file based on the error message.

**Comment by antoine19** [comment] 2019-11-22 20:50
Hello, 
Yes i do have a file "config.yml" in local.

Then also when I run:
docker run --rm -it -v "$PWD"/my_config.yml:/usr/src/app/config/config.yml:ro mtakaki/cachet-url-monitor

When i check on Kitematic, it is going to create a folder "config.yml" inside config (on my container repo) . This is where the error "Is a Directory" comes from.
--> config/config.yml
--> it runs but note with my configuration file my_config.yml ( it pings URL  http://localhost:8080/swagger instead)

The issu is i can't acces my container repo (usr\src\app\config) until i run the image.

Maybe my configuration file "my_config.yml" is not in the right place.

**Comment by mtakaki** [comment] 2019-11-23 17:46
So, I tried reproducing the same error you're getting and I only get it if I create a directory named `config.yml`, like this:
```
$ mkdir config.yml
$ docker run --rm -it -v "$PWD":/usr/src/app/config/ mtakaki/cachet-url-monitor
Traceback (most recent call last):
  File "./cachet_url_monitor/scheduler.py", line 90, in <module>
    scheduler = Scheduler(sys.argv[1])
  File "./cachet_url_monitor/scheduler.py", line 56, in __init__
    self.configuration = Configuration(config_file)
  File "/usr/local/lib/python3.7/site-packages/cachet_url_monitor-0.5-py3.7.egg/cachet_url_monitor/configuration.py", line 84, in __init__
    self.data = load(open(self.config_file, 'r'), Loader=FullLoader)
IsADirectoryError: [Errno 21] Is a directory: 'config/config.yml'
```

Could you please confirm you have a `config.yml` file (not directory) in your current directory when you're calling docker?

**Comment by antoine19** [comment] 2019-11-23 23:02
Hello,
Yes i do have a file "config.yml" in my local repository.
I think the problem is coming from the fact that i have two volumes mounted on my container:
-usr\src\app\config\
-usr\src\app\conf\

So when i run :
docker run --rm -it -v "$PWD":/usr/src/app/conf/ mtakaki/cachet-url-monitor

It runs but still with another fill.
By default it seems that it will look in this container repo and ignores the other container repo.(usr\src\app\config\)

**Comment by mtakaki** [comment] 2019-11-26 08:32
On which OS are you running this?

**Comment by antoine19** [comment] 2019-11-26 13:26
I am using Windows (not Pro).

I deleted the container and re-pull image and run the container with Kitematic.
I have now a local repo with a config.yml inside.

![Capture](https://user-images.githubusercontent.com/23458544/69637292-a6cf6e80-1058-11ea-91ce-185704cc1982.JPG)

Its running and now my issue seems to be coming from the Cachet API now.

![Capture2](https://user-images.githubusercontent.com/23458544/69637319-b2229a00-1058-11ea-8c1c-5816e5ce2337.JPG)

**Comment by mtakaki** [comment] 2019-11-26 15:40
`Name does not resolve` sounds like your domain name is incorrect. Sometimes in docker you can get dns issues, if you don't configure the dns properly on your container. Is it an internal domain name that is only resolved by your internal dns server? Or is it a public one?

**Comment by antoine19** [comment] 2019-11-26 23:08
Ok thanks, my bad i made a mistake when entering the cachet API.
I think my last issue is coming from the metric now  during the uploading.
It is weird because i do have two metric in my cachet server (with id: 1 and id: 2)
Do i need token to access them ?  Because when entering  (http://hostname/api/v1/metrics) i get them without any token ?
![Capture0](https://user-images.githubusercontent.com/23458544/69680034-030eae80-10aa-11ea-81ec-c5ac47b2501a.JPG)

**Comment by antoine19** [comment] 2019-11-29 20:52
Hi,

Indeed, i need an API token.
Ok now i have everything working fine, thank you for your help.
I was just wondering if it would be possible to monitor multiple URL at the send time with the configuration file (.yml) ?

**Comment by mtakaki** [comment] 2020-01-05 22:06
@antoine19 this is now supported on the latest release. You can refer to the readme on how to set it up.

**Comment by mtakaki** [comment] 2020-01-19 04:16
I'm closing this issue as it's not a problem anymore.

**Closed by mtakaki** 2020-01-19 04:16 UTC
Labels: question

**Comment by tayanov** [comment] 2023-01-11 11:14
before create container, make empty config file, then start container.
Because container make not file, but folder.
